Adding assignment
Gagan2095/ERC20-token pull request #1
Opened 2024-08-12 13:59 UTC by Gagan2095

Created an ERC-20 token using the hardhat framework. The contract code is written in the Contract folder, all the standards are applied to it. I moved the ignition folder in the gitignore file, and also added the README file in the branch.
There are some configurations for deployment and verification purposes which are in hardhat.config.js file. I have declared three environment variables locally in the project which are being used in the hardhat config file. Applied the standard solidity style guide and Natspec on every part of code.

2024-08-12 14:09 UTC, MoFahimKh commented
Please fix the PR description, it does not justifies the work done in the PR.

2024-08-12 14:13 UTC, MoFahimKh commented
I am unable to find a readme file in the PR.

2024-08-12 14:16 UTC, MoFahimKh requested changes
Is the ignition file required to be pushed in the repo? if not pleas remove

2024-08-12 14:16 UTC, MoFahimKh commented on test/Token.js
> +describe("Coins", function () {
write tests for all the written functions in the contract.

2024-08-12 14:23 UTC, Gagan2095 commented
> I am unable to find a readme file in the PR.

Because I first pushed the README file on main branch

2024-08-12 14:25 UTC, MoFahimKh commented
> does

add it here, will review your readme as well

2024-08-12 14:26 UTC, Gagan2095 commented
> Please fix the PR description, it does not justifies the work done in the PR.

ok

2024-08-12 14:27 UTC, Gagan2095 commented
> Is the ignition file required to be pushed in the repo? if not pleas remove

ok

2024-08-13 02:24 UTC, Gagan2095 commented
> Please fix the PR description, it does not justifies the work done in the PR.

fixed.

2024-08-13 02:26 UTC, Gagan2095 commented
> I am unable to find a readme file in the PR.

Please check now.

2024-12-14 09:05 UTC, merged